### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by jchristn** [AntikerlabAfrica/NetTCP#1]
You're going to clone Watson, rename it, and make it a new product?  And release it *under a different license*?  That's dirty.

**Comment by jchristn** [comment]
And all traces of the fact that it was forked have been removed.  Are you going to release it on NuGet next?  Thanks for taking my work and stealing it without any attribution.

**Comment by AntikerlabAfrica** [comment]
Hey initially it was forked from your WatsonTCP but we removed it again compleatly and started to build our own Library without forking anything from. If you find any code which is taked from your Library please inform us so we will delete the Code. Greetings

**Comment by jchristn** [comment]
Please accept my apologies then.  I'm sure you can appreciate how it would feel seeing that.  Wishing you a good day and best of luck.

**Comment by AntikerlabAfrica** [comment]
We understand you fully and like to apologize too if we created any confusion. If we had kept the Fork of WhatsonTCP we would, of course, Made it Clear of everyone to read that it is Forked from your Library namely WatsonTCP and had Noted your Name and also used your Original License.
We also would have put the notice in the Project we intended it for originally that WatsonTCP is your Property.
We are Sorry that it made confusion since we had named the Fork the same way before we Decided to Completely start from scratch.
Than you Very much and again we are sorry for any misunderstandings we caused.
Have a Blessed and Productive Day.
